### ISSUE TITLE
Cannot import name CvBridge

### ISSUE THREAD

**Issue by MiroAndje** [mlaiacker/rosbag2video#12]
Hallo mlaiacker ,

since a new update of my ubuntu 16.04 LTS I get the following error message while I want to create a mp4-video from a rosbag:

_Traceback (most recent call last):
  File "rosbag2video.py", line 18, in <module>
    from cv_bridge import CvBridge, CvBridgeError
ImportError: cannot import name CvBridge"_

My python version is:

_Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609] on linux2_

Could you please help me?

Best regards 
MiroslavAndje

**Comment by MiroalavAndje** [comment]
Before I works fine....

**Comment by pramodkhandalkar** [comment]
https://github.com/ros-perception/vision_opencv

install cv_bridge from custom package

**Comment by mlaiacker** [comment]
I am sorry, I don't work with ROS currently so I cant help much
