### ISSUE TITLE
Code is not working

### ISSUE THREAD

**Issue by deeplearner93** [mlaiacker/rosbag2video#16]
Dear @mlaiacker ,
Used you code, installed ffmpeg. The command executed
```
python rosbag2video.py --25 --1 -o testing.mp4 -/camera/image_raw data1.bag
```
and also 
```
python rosbag2video.py --25 --1 -o testing.mp4 data1.bag
```

After that, followed the same syntax of your given example.
```
rosbag2video.py -r 50 -o test.mp4 data1.bag
```

I did not get any output. No video file was created.
Request support. 
Thank you

**Comment by mlaiacker** [comment]
no output at all on the command line?

**Comment by mlaiacker** [comment]
I just tested the code again and it seems to work fine and i also refactored a lot to make it nicer and run with python3.
try to pull the new version and read the readme to install the required dependencys

**Comment by deeplearner93** [comment]
@mlaiacker. Thank you for the Reply. I have all dependencies installed and all are fine. Can you share the correct command once again. ?

**Comment by cardboardcode** [comment]
Based on the last response, it seems this issue has been resolved. 

Closing issue.
