### ISSUE TITLE
arg parse error

### ISSUE THREAD

**Issue by zhixuan-wei** [mlaiacker/rosbag2video#18]
https://github.com/mlaiacker/rosbag2video/blob/3a7b44208a430b9e0dd1d01ae4eb7350341bfdf7/rosbag2video.py#L82-L85

should be 

```
            elif opt in ("--fps"):
                self.fps = float(arg)
            elif opt in ("-r", "--rate"):
                self.rate = float(arg)
```

**Comment by cardboardcode** [comment]
Thank you for pointing this out. @zhixuan-wei. It has been fixed in the above commit.
