### ISSUE TITLE
I Can't extract the video from bag file

### ISSUE THREAD

**Issue by yellowjs0304** [mlaiacker/rosbag2video#6]
Hello I did the command
`./rosbag2video.py -r 50 -o test.mp4 MYBAG.bag`
It returns
```
using  50.0  FPS
############# USING ######################
camera/rgb/image_raw  with datatype: sensor_msgs/Image
############# USING ######################
camera/depth_registered/image_raw  with datatype: sensor_msgs/Image
unsuportet encoding: bayer_grbg8
```
How Can I Fix this problem?

**Comment by Maxinjun** [comment]
@yellowjs0304 Have you got the solution? I also meet the same issue as following 
maxj@ubuntu:~/rosbag2video$ python rosbag2video.py -t /stereo_camera/left/image_raw_throttle/compressed ~/test.bag 
using  25.0  FPS
############# USING ######################
/stereo_camera/left/image_raw_throttle/compressed  with datatype: sensor_msgs/CompressedImage

**Comment by yellowjs0304** [comment]
@Maxinjun Sorry, but I didn't get any solution.
