### ISSUE TITLE
unsuportet encoding: 8UC1

### ISSUE THREAD

**Issue by izengpan** [mlaiacker/rosbag2video#8]
Hello，thanks for your great work.
I'm writing to ask a question.
I have followed your steps, and the final result is:
----------------------------------------------------------------------------------
preproc_tf.bag
using  25.0  FPS
############# USING ######################
/rect_color_raw  with datatype: sensor_msgs/Image
############# USING ######################
/cnn_label  with datatype: sensor_msgs/Image
unsuportet encoding: 8UC1
----------------------------------------------------------------------------------
It seems there are something wrong with the pictures' format.
Have you meet this problem before? and do you have any ideas?

**Comment by mlaiacker** [comment]
I have not seen this problem before. have you tryed to only convert the "/rect_color_raw" topich by using the -t parameter
example: 
rosbag2video -t /rect_color_raw preproc_tf.bag

**Comment by mlaiacker** [comment]
I have not used the script for a while so maybe something changed in ros
