### ISSUE TITLE
Support Ubuntu 18.04

### ISSUE THREAD

**Issue by J-Rojas** [mlaiacker/rosbag2video#9]
The package 'libav-tools' does not exist in Ubuntu 18.04; it has been replaced with the 'ffmpeg' package. Replacing the command 'avconv' with 'ffmpeg' will work. 

https://askubuntu.com/questions/1098407/how-do-you-install-avconv-on-ubuntu-18-04

**Comment by mlaiacker** [comment]
is fixed with the latest pull request
